# Tốc độ xử lý của NumPy

Gấp 10 đến 100 lần so với Python thuần túy

In [12]:
my_list = list(range(1000000))
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 3.44 s
Wall time: 3.46 s


In [13]:
import numpy as np
my_arr = np.arange(1000000)
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 62.5 ms
Wall time: 43.3 ms


# Mảng đa chiều (N-dimensional array object)

NumPy cho phép thực hiện các phép toán trên mảng tương tự các phép toán trên số thực

In [14]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
 

In [5]:
data = np.random.randn(2, 3)
data

array([[-0.75885339,  1.00155592, -0.0508053 ],
       [-0.31634825,  0.4302599 , -1.22893046]])

In [6]:
type(data)

numpy.ndarray

In [7]:
data * 2

array([[-1.51770678,  2.00311185, -0.10161059],
       [-0.6326965 ,  0.86051979, -2.45786091]])

In [8]:
data + data

array([[-1.51770678,  2.00311185, -0.10161059],
       [-0.6326965 ,  0.86051979, -2.45786091]])

# Cách khởi tạo mảng trong NumPy

Sử dụng phương thức array để chuyển mảng trong Python qua mảng trong NumPy

In [9]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [16]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 
arr2 = np.array(data2)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Các thuộc tính của đối tượng ndarray

In [12]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
arr1.ndim

1

In [14]:
arr1.shape

(5,)

In [19]:
arr1.dtype

dtype('float64')

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [20]:
arr2.dtype

dtype('int32')

In [20]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [21]:
# tao ndarray tu data2 voi dtype=float64
arr3 = np.array(data2, dtype=np.float64)
arr3

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

# Cách khởi tạo mảng trong NumPy

Khởi tạo mảng đa chiều với các phần tử ‘0’

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
arr4 = np.empty((2, 3, 3))
arr4

array([[[ 1.72723371e-077,  1.72723371e-077,  7.90505033e-323],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 1.35617292e+248, -2.32036159e+077,  1.72723371e-077]]])

In [25]:
np.empty([2, 2], dtype=np.float64)

array([[6. , 7.5],
       [8. , 1. ]])

In [26]:
# type upcasting
arr3 = np.array([1, 2, 3], dtype=np.float64)
arr3

array([1., 2., 3.])

In [27]:
# type downcasting
arr3 = np.array([1.5, 2.9, 3.0], dtype=np.int64)
arr3

array([1, 2, 3])

In [28]:
# check np version
np.__version__

'1.19.5'

Kiểu dữ liệu trong NumPy

In [29]:
numeric_strings = np.array(['1.25', '-9.6', '42'])

In [30]:
numeric_strings

array(['1.25', '-9.6', '42'], dtype='<U4')

In [31]:
numeric_strings1 = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [32]:
numeric_strings1

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [33]:
help(np.ndarray.astype)

Help on method_descriptor:

astype(...)
    a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
    
    Copy of the array, cast to a specified type.
    
    Parameters
    ----------
    dtype : str or dtype
        Typecode or data-type to which the array is cast.
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout order of the result.
        'C' means C order, 'F' means Fortran order, 'A'
        means 'F' order if all the arrays are Fortran contiguous,
        'C' order otherwise, and 'K' means as close to the
        order the array elements appear in memory as possible.
        Default is 'K'.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur. Defaults to 'unsafe'
        for backwards compatibility.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are allowed.
          * 'safe' means only cas

In [34]:
numeric_strings2 = numeric_strings1.astype(float)
numeric_strings2

array([ 1.25, -9.6 , 42.  ])

# Toán tử vecto hoá (element-wise)

In [35]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) 
print(arr)
print(arr*arr)
print(arr-arr)
print(1/arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [36]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]]) 
tmp = arr>arr2
tmp

array([[ True, False,  True],
       [False,  True, False]])

Để thao tác với các phần tử hay các tập con trong mảng của NumPy, ta thao tác như List của Python

In [33]:
arr = np.arange(10) 
print(arr)
print(arr[5]) 
print(arr[5:-1])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7 8]


In [37]:
type(arr)

numpy.ndarray

Dùng mảng Boolean để tạo mảng con cho 1 mảng khác nếu như có cùng chiều dài như nhau

In [163]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', ' Joe', 'Joe'])
data = np.random.randn(7, 4) 
print(names)
print(data)
print(names=='Bob')
# tao mang moi tu mang data gom cac hang co chi so tuong ung voi vị tri names='Bob'
new_arr = data[names=='Bob']
new_arr

['Bob' 'Joe' 'Will' 'Bob' 'Will' ' Joe' 'Joe']
[[ 0.28714875 -1.34582443  1.26471462  0.63531478]
 [ 0.25837279 -0.03743991  1.82480734  0.68936864]
 [ 1.07962589  0.43092953  2.34047807 -0.99445121]
 [-0.42523807 -0.68725076  0.92909071  1.04587529]
 [-0.09161419 -0.26427477 -0.53141598 -1.37946598]
 [ 0.98679693 -1.26301183  0.36253201 -0.88786856]
 [ 1.81365018  1.2005056  -1.43825485 -1.49412165]]
[ True False False  True False False False]


array([[ 0.28714875, -1.34582443,  1.26471462,  0.63531478],
       [-0.42523807, -0.68725076,  0.92909071,  1.04587529]])

In [164]:
print(data[names == 'Bob', 2:])

[[1.26471462 0.63531478]
 [0.92909071 1.04587529]]


In [166]:
tmp = data[names == 'Bob', 3]
print(tmp)

[0.63531478 1.04587529]


In [167]:
tmp.shape

(2,)

In [168]:
data < 0

array([[False,  True, False, False],
       [False,  True, False, False],
       [False, False, False,  True],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [False,  True, False,  True],
       [False, False,  True,  True]])

In [170]:
print(data)
data[data<0] = 0
print(data)

[[ 0.28714875 -1.34582443  1.26471462  0.63531478]
 [ 0.25837279 -0.03743991  1.82480734  0.68936864]
 [ 1.07962589  0.43092953  2.34047807 -0.99445121]
 [-0.42523807 -0.68725076  0.92909071  1.04587529]
 [-0.09161419 -0.26427477 -0.53141598 -1.37946598]
 [ 0.98679693 -1.26301183  0.36253201 -0.88786856]
 [ 1.81365018  1.2005056  -1.43825485 -1.49412165]]
[[0.28714875 0.         1.26471462 0.63531478]
 [0.25837279 0.         1.82480734 0.68936864]
 [1.07962589 0.43092953 2.34047807 0.        ]
 [0.         0.         0.92909071 1.04587529]
 [0.         0.         0.         0.        ]
 [0.98679693 0.         0.36253201 0.        ]
 [1.81365018 1.2005056  0.         0.        ]]


Fancy Indexing

NumPy cho phép tạo 1 mảng con theo chỉ mục cho trước

In [40]:
names = np.array(['Tuan', 'Phuong', 'Khoi', 'Hieu', 'Duy' , 'Thang', 'Duc'])
print(names)
# tao mang moi tu mang names gom cac ptu co index 0,5,4 cua dim1
print(names[[0,4,5]])

['Tuan' 'Phuong' 'Khoi' 'Hieu' 'Duy' 'Thang' 'Duc']
['Tuan' 'Phuong' 'Khoi' 'Hieu']


In [173]:
data

array([[0.28714875, 0.        , 1.26471462, 0.63531478],
       [0.25837279, 0.        , 1.82480734, 0.68936864],
       [1.07962589, 0.43092953, 2.34047807, 0.        ],
       [0.        , 0.        , 0.92909071, 1.04587529],
       [0.        , 0.        , 0.        , 0.        ],
       [0.98679693, 0.        , 0.36253201, 0.        ],
       [1.81365018, 1.2005056 , 0.        , 0.        ]])

In [176]:
# tao mang moi tu mang names gom cac ptu co index 0,1,2,3 cua dim1 và 0,1,2,3 cua dim2
data[[0,1,2,3],[0,1,2,3]]

array([0.28714875, 0.        , 2.34047807, 1.04587529])

In [177]:
# tao mang moi tu mang names gom cac ptu co index 6 cua dim1 và 1 cua dim2
data[6,1]

1.2005056039527984

In [183]:
# chuyen array 1x32 thanh arr 8x4
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [199]:
print(arr[[1, 5, 7, 2]]) # lay 4 hang 1,5,7,2
print()
print(arr[[1, 5, 7, 2]] [:, :]) # lay 4 hang 1,5,7,2 va tat ca cot
print(arr[[1, 5, 7, 2]] [:, [0, 3]]) # lay 4 hang 1,5,7,2 va cot 0, 3

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[ 4  7]
 [20 23]
 [28 31]
 [ 8 11]]


Ma trận chuyển vị

In [200]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [201]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [202]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [203]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpose(x, (1, 0, 2)).s

In [234]:
arr = np.arange(16).reshape((2, 8))
print(arr)
print('-----')
print(arr.T)
print('-----')
print(arr.transpose())
print('-----')
print(arr.swapaxes(0, 1))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
-----
[[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]
-----
[[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]
-----
[[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]


In [238]:
arr1 = np.arange(16).reshape((2, 8))
arr2 = np.arange(16).reshape((2, 8))
arr_sum1 = arr1 + arr2
arr_sum2 = np.add(arr1,arr2)
arr_sum1 == arr_sum2

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
points = np.arr